### ISSUE TITLE
[BUG]The exception is unfriendly(Mapper parsing exception) when k-NN circuit breaker is triggered

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/k-NN#1424]
**What is the bug?**
During bulk indexing, when k-NN circuit breaker is triggered, client receive mapper_parsing_exception. This makes user hard to understand the actual root cause of the exception until they look in to a log file.

**How can one reproduce the bug?**
```
"type": "knn_vector",
"dimension": 256,
"method": {
    "name": "hnsw",
    "engine": "faiss",
    "space_type": "innerproduct",
    "parameters": {
        "ef_construction": 100,
        "m": 16
    }
}
```

Do bulk indexing of documents

```
Error message from client side
failed to parse field [passageVector] of type [knn_vector] in document with id 'asdfasdf'. mapper_parsing_exception'
Preview of fields's value: '[1.23232, 2.123232. ...]', statusCode: 400, type: mapper_parsing_exception
```

```
Log
MapperParsingException[failed to parse field [passageVector] of type [knn_vector] in document with id 'asdfasdf'. Preview of field's value: '[1.23232, 2.123232, ...]']; nested: IllegalStateException[Indexing knn vector fields is rejected as circuit breaker triggered. Check _opendistro/_knn/stats for detailed state];
```
**What is the expected behavior?**
It should provide the root cause of the exception, k-NN circuit breaker in client side error message

**Comment by navneet1v** [comment]
@heemin32 how this is bug? I would consider this as an enhancement where messaging is not proper.

**Comment by heemin32** [comment]
It is a bug because the error message is not correct. If the exception is InternalException or ThrottlingException, it is not a bug. However, mapper parsing exception does not encompass circuit breaker exception but those two are entirely different exceptions.

**Comment by ryanbogan** [comment]
Following a deep dive, we throw the nested circuit breaker exception in KNNVectorFieldMapper [here](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L625-L631).  This method is called within a parseCreateField [method](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L546).  Tracing the method calls, we eventually arrive at the parse [method](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/FieldMapper.java#L267-L306) in the FieldMapper class of the OpenSearch repository, which calls the method in a try/catch and wraps any exception that is caught .  The parseCreateField method is the only place we can check if our circuit breaker is triggered before indexing begins.  The parsing action fails because the circuit breaker is triggered, so the exception is technically correct.  That being said, I think we should create a new type of exception to throw instead of an illegal state: `KNNCircuitBreakerException`.  I also think we can improve the wording of the nested exception message to more clearly describe to the user what action is failing and what it means for their cluster.

**Comment by nwatab** [comment]
Does that mean simply reducing bulk batch size could avoid the error?
