### ISSUE TITLE
[BUG] ldconfig only runs in linux, not on macOS

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/k-NN#254]
The command here:
https://github.com/opensearch-project/k-NN/blob/15b06fa3740e1cef2f8d8d5585e66ff46b467a20/scripts/build.sh#L106

```
ompPath=$(ldconfig -p | grep libgomp | cut -d ' ' -f 4)
```

ldconfig is a linux specific command, and since build workflow is allowed to run on macOS with --platform linux, we should add a exception to allow macOS also run similar, or at least alert this can only be run on linux for now.

libomp doesnt seems to present on macOS and I am not sure where it is coming from, otool on macOS does not show anything similar.

Even on a linux I dont see libomp in ldconfig -p, so I would assume it is coming after jni lib has been built.

Thanks.

**Comment by jmazanec15** [comment]
Hi @peterzhuamazon 

I dont think building the k-NN libraries on Mac for linux will work. We do not have any special cross compiling logic in our CMake so I do not think that building .so files will be possible. That being said, I think k-NN build logic should  be skipped.

> or at least alert this can only be run on linux for now.

How do you suggest we check this? Just parsing output of some `uname` command? Also, can you provide more specific expected behavior of this script in the case you mentioned?

On linux, the OpenMP dependency needs to be installed before running `ldconfig -p`.

**Comment by peterzhuamazon** [comment]
Hi @jmazanec15 as of now I can reproduce everything on macOS until I reach the above 106 line and error out due to command not find.

I was not aware you cannot cross compile this lib on macOS and I have to setup a linux env again to test my code.

That being said, I think there will be community members have the same experience on their macOS and would have this confusion, so just open this issue and address my concern.

@dblock any input you can give on this? We can reproduce all the linux builds on macOS except this KNNLIB part with --platform linux as of now.

Thanks.
