### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by chenjia123** [opensearch-project/k-NN#434]
Why not support [google-research/scann](https://github.com/google-research/google-research/tree/master/scann)?

**Comment by jmazanec15** [comment]
Hi @chenjia123, I have taken a look into ScANN and its very interesting. There are a couple reasons we don't support it right now:
1. Implementation is designed only for x86 - the plugin needs to work on ARM.
2. In docs, it says "The code is released for research purposes" - So, Im not sure if its stable enough for production use yet.
3. Haven't had enough user demand for it yet - it would require a good amount of effort to add.

That being said, in the future, it would be interesting to make the backend KNN library the plugin uses more pluggable so that users could experiment with different implementations.
