### ISSUE TITLE
Investigate using GetPrimitiveArrayCritical in JNI

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#74]
## Description
Opening up issue based on this discussion: https://github.com/opendistro-for-elasticsearch/k-NN/pull/317

In the JNI, we make calls to get arrays from Java using [Get<Primitive>ArrayElements](https://github.com/opensearch-project/k-NN/blob/main/jni/src/org_opensearch_knn_index_v2011_KNNIndex.cpp#L121). This may or may not return a copy of the array. Copying is expensive and unnecessary for read-only data. As an alternative, we could use [GetPrimitiveArrayCritical](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetPrimitiveArrayCritical_ReleasePrimitiveArrayCritical), which makes it more likely that a reference is returned as opposed to a copy. However, this method seems riskier and has several restrictions.

I wanted to hear from the community on their thoughts on this @flyingpot.

**Comment by flyingpot** [comment]
I have found something wrong happens when using GetPrimitiveArrayCritical. If a lot of vectors are dumped to index, GetPrimitive methods will cause [GCLocker](https://shipilev.net/jvm/anatomy-quarks/9-jni-critical-gclocker/), and will make allocate memory pause for a long time. 
In my experiment, Netty get stuck in allocating memory, leader/follower checks fail and nodes are kicked out of cluster.

**Comment by jmazanec15** [comment]
I see that is interesting. @flyingpot could you describe your experiment setup?

**Comment by Hamlin-Li** [comment]
I think this future feature can help eliminate the issue: https://bugs.openjdk.java.net/browse/JDK-8276094
