### ISSUE TITLE
Support for dot product when using lucene as an engine for approximate-knn

### ISSUE THREAD

**Issue by jn2clark** [opensearch-project/k-NN#865]
**Is your feature request related to a problem? Please describe.**
The problem is when using Lucene as an engine for approximate-knn there is no support for dot product as a similarity measure. See here https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/. This is a very common measure and the forced normalization that cosine provides prevents some use cases. There are also less computations required.

**Describe the solution you'd like**
Support for dot product when Lucene is used as an engine for knn indexes. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pandu-k** [comment]
Hi all!

Just got a couple of questions: 

1. Is there an estimated release for this feature? 
2. Are there any risks that dot product will be incompatible with OpenSearch as it's possible for it to be negative? Is there anyway to mitigate this risk?

**Comment by jn2clark** [comment]
@pandu-k I think the risk can be mitigated be encouraging (but not forcing) folks to normalize the vectors _at indexing time_ rather than at search time. The forced normalization at search time is overly restrictive IMO and restricts the usefulness of the vector search

**Comment by jn2clark** [comment]
Thanks for the update @jmazanec15 . I understand the reasons but want to re-iterate that from a vector search perspective this will impact a number of use cases.

**Comment by jmazanec15** [comment]
@jn2clark for your use case, will you always normalize the vectors before using the dot product? It seems if there are enough valid use cases for non-normalized dot product search, we could see if lucene would take the change directly.

**Comment by pandu-k** [comment]
@jmazanec15 it's pretty straightforward to ensure that all vectors are normalised before being indexed

**Comment by jn2clark** [comment]
@jmazanec15  yes

**Comment by jmazanec15** [comment]
@pandu-k It might be straightforward to implement, but it will add additional overhead to indexing, hurting overall system throughput. So I would like to avoid that.

> But even if the vectors weren't normalised, would that cause any structural issues with the HNSW graph?

No, it is just a distance metric so it wont matter, so I dont think it will matter. In fact, for normalized vectors, it should operate in the same way.

In general, my preference would be to update [compare](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java#L44-L61) to use a method like:
```
if (dotProduct < 0) {
  return 1 / (1 + -1*dotProduct);
}
return dotProduct + 1;
```

Instead of:
```
return (1 + dotProduct(v1, v2)) / 2;
```

Overall, this would preserve the ordering as well as keep the distance positive. However, it might add a few extra computations.

However, Im wondering if it is a reasonable assumption for dotProduct spaces to always be normalized - if this is the case, it might not make sense to make the change at all. @jn2clark do you have any opinion on this?

**Comment by jn2clark** [comment]
I don't know if you can assume they are always normalized but you can recommend that. It's worth noting that this similarity metric is available in the knn plugin for nmslib and faiss already. This should serve as a pretty good example to follow or is there something special about lucene as an engine? Adopting the same convention as those might be the best from a consistency and user expectation perspective. 
https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/
https://opensearch.org/docs/latest/search-plugins/knn/knn-index#method-definitions

**Comment by jmazanec15** [comment]
The implementation of the query is in Lucene so we would need to change functionality over there to get it to work. I created an issue. We can see what they think.

**Comment by navneet1v** [comment]
I have raised a PR to support dot product with Lucene engine: https://github.com/opensearch-project/k-NN/issues/865

**Comment by jmazanec15** [comment]
This is in https://github.com/opensearch-project/k-NN/commits/2.13/. I think this can be closed.
